<form action="<?php echo Link::url("game/".SID."/notepad.index/delete") ?>" method="post">
	<table class="ntable">
		<thead>
			<tr>
				<th colspan="3">{lang=NOTEPAD}</th>
			</tr>
			<tr>
				<th>{lang=SUBJECT}</th>
				<th>{lang=DATE}</th>
				<th>{lang=DELETE}</th>
			</tr>
		</thead>
		<tfoot>
			<tr>
				<td class="center" colspan="3">
					<button class="button" type="submit">{lang=DELETE_MARKED}</button>
					<button type="button" class="button" onclick="location.href = '<?php echo Link::url("game/".SID."/notepad.index/add") ?>'">{lang=CREATE}</button>
				</td>
			</tr>
		</tfoot>
		<tbody>
			<?php foreach($this->getLoop("notes") as $note): ?>
			<tr>
				<td><?php echo Link::get("game/".SID."/notepad.index/show/".$note->getId(), $note->getTitle()) ?></td>
				<td><?php echo Date::timeToString(1, $note->getTimeCreated()) ?></td>
				<td><input type="checkbox" name="notes[]" value="<?php echo $note->getId() ?>"/></td>
			</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</form>